# Generated by Django 5.2.7 on 2025-10-31 10:12

import certificates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=certificates.models.upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=certificates.models.generated_doc_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.uploadedpdf')),
            ],
        ),
    ]
