# Generated by Django 5.2.7 on 2025-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Template', max_length=255)),
                ('file', models.FileField(upload_to='templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('placeholders', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
