# Generated by Django 5.2.7 on 2025-10-31 12:12

import certificates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificatetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='generatedcertificate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='body_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='engine_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='insurance_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_certificates', to='certificates.certificatetemplate'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='file',
            field=models.FileField(upload_to=certificates.models.template_upload_path),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(default='Certificate Template', max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='uploaded_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.uploadedpdf'),
        ),
    ]
