# Generated by Django 5.2.7 on 2025-10-31 12:41

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificatetemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcertificate',
            name='file',
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=certificates.models.generated_doc_path),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=certificates.models.generated_doc_path),
        ),
    ]
