# Generated by Django 5.2.7 on 2025-11-03 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_remove_generatedcertificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='certificate_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
