# Generated by Django 5.2.7 on 2025-11-04 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_generatedcertificate_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='certificate_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
