# Generated by Django 5.2.7 on 2025-11-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_generatedcertificate_certificate_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedcertificate',
            options={},
        ),
    ]
