# Generated by Django 5.2.7 on 2025-11-04 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_alter_generatedcertificate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 11, 4)),
        ),
    ]
