# Generated by Django 5.2.7 on 2025-12-17 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_generatedcertificate_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='file',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='placeholders',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_templates/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='workflow_type',
            field=models.CharField(choices=[('installation', 'Installation'), ('deinstallation', 'De-installation')], default='installation', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 12, 17)),
        ),
    ]
