# Generated by Django 5.2.7 on 2025-12-17 14:09

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_certificatetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='active',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='docx_file',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='workflow_type',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=certificates.models.template_upload_path),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='placeholders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(default='Certificate Template', max_length=255),
        ),
    ]
