# Generated by Django 5.2.7 on 2025-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_alter_certificatetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
