# Generated by Django 5.2.7 on 2025-12-18 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_generatedcertificate_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='imei',
            field=models.CharField(blank=True, help_text='Tracker IMEI number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 12, 18)),
        ),
    ]
