# Generated by Django 5.2.7 on 2025-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_generatedcertificate_imei_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcertificate',
            name='imei',
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='imei_1',
            field=models.CharField(blank=True, help_text='Tracker IMEI number 1 (max 15 chars)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='imei_2',
            field=models.CharField(blank=True, help_text='Tracker IMEI number 2 (max 15 chars)', max_length=15, null=True),
        ),
    ]
